### Generated by rprotoc. DO NOT EDIT!
### <proto file: proto/user.proto>
# package proto;
# 
# message User {
# 	optional string guid = 1;
# }
# 
# message UserList {
# 	repeated User users = 1;
# }
# 
# message UserFindRequest {
# 	repeated string guids = 1;
# }
# 
# service UserService {
# 	rpc find (UserFindRequest) returns (UserList);
# 	rpc create (User) returns (User);
# }
require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

module Proto
  class User < ::Protobuf::Message
    defined_in __FILE__
    optional :string, :guid, 1
  end
  class UserList < ::Protobuf::Message
    defined_in __FILE__
    repeated :User, :users, 1
  end
  class UserFindRequest < ::Protobuf::Message
    defined_in __FILE__
    repeated :string, :guids, 1
  end
end